# Load the packages

library(dplyr)
library(shiny)
library(shinydashboard)
library(ggplot2)
library(plotROC)
library(broom)
library(DT)
library(msigdbr)
library(data.table)
library(shinyWidgets)
library(rintrojs)
library(readxl)

roc_ui <- function(id, label, choices) {
  ns <- NS(id)
  tagList(
    
    useShinyalert(),
    
    add_busy_spinner(
      spin = "cube-grid",
      position = "top-right",
      color = "#01303f",
      margins = c(300, 500),
      height = "60px",
      width = "60px"),
    
    sidebarPanel(
      selectizeInput(inputId =ns("roc_definition_sel"), 
                     multiple=T,
                     label = "Select sample types",
                     choices=NULL, # will be updated dynamically
                     options=list(placeholder = "eg. Primary solid tumor")),
      selectizeInput(inputId =  ns("selectore"),
                     label= "Choose response variable",
                     choices = NULL,
                     multiple = FALSE),
      conditionalPanel(
        condition = "input.selectore == 'Categorical Values'",
        ns=ns,
        selectizeInput(inputId =  ns("binaryone"),
                       label= "Choose categorical data",
                       choices = NULL,
                       multiple = FALSE,
                       options=list(placeholder = "eg. meta.definition")),
        selectizeInput(inputId =  ns("binarytwo"),
                       label= "Choose values to binarized as 1 (desired outcome).",
                       choices = NULL,
                       multiple = TRUE,
                       options=list(placeholder = "eg. Solid Tissue Normal")),
        selectizeInput(inputId =  ns("binarythree"),
                       label= "Choose values to binarize as 0 (undesired outcome)",
                       choices = NULL,
                       multiple = TRUE,
                       options=list(placeholder = "eg. Primary solid tumor")),
      ),
      conditionalPanel(
        condition= "input.selectore == 'Numeric Values'",
        ns=ns, 
        selectizeInput(inputId =  ns("one_gene"),
                       label= "Choose numeric data",
                       choices = NULL,
                       multiple = FALSE,
                       options=list(placeholder = "eg. CD8A")),
        
        numericInput(inputId = ns("hi_cutoff_covar"), "High cutoff percent (Samples in this group will be binarized as 1)", 50, 1, 100),
        
        numericInput(inputId = ns("lo_cutoff_covar"), "Low cutoff percent (samples in this group will be binarized as 0)", 50, 1, 100)
        
        
      ),
      selectizeInput(inputId = ns("roc_gene_selector"),
                     label= "Specify method for selecting predictors",
                     choices = c("Manually enter gene names", "Upload a xlsx/xls file"),
                     multiple = FALSE),
      conditionalPanel(
        condition = "input.roc_gene_selector == 'Manually enter gene names'",
        ns=ns,
        selectizeInput(inputId =  ns("genesss"), #Gene sets generated by user.
                       label= "Select variable(s) to create a custom predictor (multiple variables will be averaged)",
                       choices = NULL,
                       multiple = TRUE,
                       options=list(placeholder = "eg. TSPAN6, TNMD etc."))
      ),
      conditionalPanel(
        condition = "input.roc_gene_selector == 'Upload a xlsx/xls file'",
        ns=ns,
        fileInput(ns("roc_csv"), 
                  # label = "3. Please upload your xlsx/xls file.",
                  label = tags$span(
                    "Please upload your xlsx/xls file.", 
                    tags$i(
                      class = "glyphicon glyphicon-info-sign", 
                      style = "color:#0072B2;",
                      title = "The xlsx/xls file should contain one unnamed column: the first column should contain the gene names."
                    ), tags$br(),
                    a(href="sample_gene_input.xlsx", "Sample Input File", download=NA, target="_blank")
                    ),
                  accept = c(".xls", ".xlsx"),
                  multiple = FALSE))
        # a(href="roc_input_sample.xlsx", "Download Sample File", download=NA, target="_blank"))
      ,
      materialSwitch(inputId = ns("show_msigdb_gene_sets"),
                     label = "Add MSigDB sets as a second predictor",
                     status = "success",
                     value = FALSE),
      conditionalPanel(
        condition = "input.show_msigdb_gene_sets == true",
        ns = ns,
        selectizeInput(ns("cate"), "Please select an MSigDB Collection", choices = c("Hallmark gene sets (H)" = "H",
                                                                                        "Positional gene sets (C1)" = "C1",
                                                                                        "Curated gene sets (C2)" = "C2",
                                                                                        "Regulatory target gene sets (C3)" = "C3",
                                                                                        "Computational gene sets (C4)" = "C4",
                                                                                        "Ontology gene sets (C5)" = "C5" ,
                                                                                        "Oncogenic gene sets (C6)" = "C6",
                                                                                        "Immunologic gene sets (C7)" = "C7",
                                                                                        "Cell type signature gene sets (C8)" = "C8",
                                                                                     "Immunotherapy signatures" ="Immunotherapy_signatures")),
        conditionalPanel(condition = "input.cate == 'C2'|input.cate =='C3'|
                                      input.cate =='C4'|
                                      input.cate =='C5'|
                                      input.cate =='C7'| 
                                      input.cate == 'Immunotherapy_signatures'", ns = ns, 
                         selectizeInput(ns("roc_subcat"),"Please select a subcategory" ,choices = c(""))
        ),
        selectizeInput(ns("roc_chosen_pathway"), #Automatically updates to show subset.
                       "Select a specific gene set", 
                       choices = NULL)
      ),
      # p("Please click the ROC button after each change to refresh the plot and tables!"),
      actionBttn(inputId = ns("roc_run"), 
                 label = "Analyze",
                 style = "unite",
                 block = TRUE,
                 color = "primary"),
      br(),
      
      downloadButton(ns("downloadPlot5"), "Download ROC Plot", style="color: #eeeeee; background-color: #01303f; border-color: #01303f"),
      
      #help section UI
      
      introjsUI(),
      actionButton(ns("roc_help"), "App Tutorial", style="color: #FFFFFF; background-color: #81A1C1; border-color: #02a9f7"),
      
      textOutput(ns("filewarning_5")) ,
      
      width = 3
      
    ),
    mainPanel(
      plotOutput(outputId = ns("multi_plot"), width = "800px", height = "500px"), #ROC plot.
      DT::dataTableOutput(outputId = ns("auctable")), #Area Under Curve (AUC) value table from ROC plot.
      DT::dataTableOutput(outputId = ns("intersect_genes_table")), #Intersected genes table between the xlsx/xls file and the data.
      DT::dataTableOutput(outputId = ns("gene_set_table")) #Selected MSigDB gene names as a table.
    )
  )
}

roc_server <- function(id, Xproj) {
  moduleServer(
    id,
    function(input, output, session) {
      
      ns <- session$ns
      
      output$filewarning_5 <- renderText({
        
        if (!is.null(Xproj$fileInfost())) {
          shinyalert("Warning!", "To perform this analysis using MsigDB gene sets, please ensure that your uploaded data set contains gene symbols rather than Entrez or Ensembl gene IDs. Otherwise you may receive errors.") }
      })
      
      #Server part for app tutorial 
      
      roc_help_tutorial <- reactive({
        
        if(input$selectore == "Numeric Values"){
          
          return(
            
            if(input$roc_gene_selector == "Manually enter gene names"){
              
              data.frame(
                
                element = paste0("#", session$ns(c(NA, "roc_definition_sel + .selectize-control", "selectore + .selectize-control", "one_gene + .selectize-control ", NA, NA,  "genesss + .selectize-control ", NA, NA))),
                
                intro = paste(c(
                  "This is the ROC (receiver operating characteristic) analysis module. In this module, you can binarize samples based on gene expression or categorical meta data and test the predictive power of a custom variable. ROC plots show True Positive Rate (TPR) and False Positive Rate (FPR) along the y- and x-axes, respectively. A completely random classifier would appear along the diagonal line in the graph and would have Area Under the Curve (AUC) of 0.5. The curve for a good positive predictor appears in the top half of the plot (AUC > 0.5), and the curve for a good negative predictor appears in the bottom half (AUC < 0.5). Continue the tutorial to learn how to use this module.",
                  "Select sample types here to focus the analysis on specific subsets.",
                  "ROC analysis is performed between two classes in the response variable as '1' (desired outcome group) and '0' (undesired outcome group). You can specify these classes for both categorical and numeric variables in the TCGA data. Here you need to select what kind of response variable you are interested in.",
                  "Select the numerical variable you want to binarize here",
                  "High cutoff input allows you to assign samples to group-1 if their values are more than the specified quantile here. For instance setting this value to 25 would mean binarizing the top 25% of the data as '1'. If you want to binarize at the median value this value should be 50 (default)",
                  "Low cutoff input allows you to assign samples to group-0 if their values are less than the specified quantile here. For instance setting this value to 25 would mean binarizing the bottom 25% of the data as '0'. If you want to binarize at the median value this value should be 50 (default)",
                  "Here, you select the predictor variable. If you enter more than one variable, their values will be averaged.",
                  "If desired, the average expression value of a specific MSigDB gene set can be added to the graph. <i> Note: You need to click on and activate 'Add MSigDB sets as a second predictor' button</i>",
                  "If you would like to include a curve for a specific MSigDB gene set, select it here."
                ))
              )
              
              
            } else if (input$roc_gene_selector ==  "Upload a xlsx/xls file") {
              
              data.frame(
                
                element = paste0("#", session$ns(c(NA, "roc_definition_sel + .selectize-control", "selectore + .selectize-control", "one_gene + .selectize-control ", NA, NA,  "roc_csv + .selectize-control ", NA, NA))),
                
                intro = paste(c(
                  "This is the ROC (receiver operating characteristic) analysis module. In this module, you can binarize samples based on gene expression or categorical meta data and test the predictive power of a custom variable. ROC plots show True Positive Rate (TPR) and False Positive Rate (FPR) along the y- and x-axes, respectively. A completely random classifier would appear along the diagonal line in the graph and would have Area Under the Curve (AUC) of 0.5. The curve for a good positive predictor appears in the top half of the plot (AUC > 0.5), and the curve for a good negative predictor appears in the bottom half (AUC < 0.5). Continue the tutorial to learn how to use this module.",
                  "Select sample types here to focus the analysis on specific subsets.",
                  "ROC analysis is performed between two classes in the response variable as '1' (desired outcome group) and '0' (undesired outcome group). You can specify these classes for both categorical and numeric variables in the TCGA data. Here you need to select what kind of response variable you are interested in.",
                  "Select the numerical variable you want to binarize here",
                  "High cutoff input allows you to assign samples to group-1 if their values are more than the specified quantile here. For instance setting this value to 25 would mean binarizing the top 25% of the data as '1'. If you want to binarize at the median value this value should be 50 (default)",
                  "Low cutoff input allows you to assign samples to group-0 if their values are less than the specified quantile here. For instance setting this value to 25 would mean binarizing the bottom 25% of the data as '0'. If you want to binarize at the median value this value should be 50 (default)",
                  "You can upload a xlsx/xls file including your genes of interest to see them as a ROC curve. If you enter more than one variable, their values will be averaged.",
                  "If desired, the average expression value of a specific MSigDB gene set can be added to the graph. <i> Note: You need to click on and activate 'Add MSigDB sets as a second predictor' button</i>",
                  "If you would like to include a curve for a specific MSigDB gene set, select it here."
                ))
              )
              
            }
          )
        } else {
          return(
            
            if(input$roc_gene_selector == "Manually enter gene names"){
              
              data.frame(
                
                element = paste0("#", session$ns(c(NA, "roc_definition_sel + .selectize-control", "selectore + .selectize-control", "binaryone + .selectize-control ", "binarytwo + .selectize-control ", "binarythree + .selectize-control ", "genesss + .selectize-control ", NA, NA))),
                
                intro = paste(c(
                  "This is the ROC (receiver operating characteristic) analysis module. In this module, you can binarize samples based on gene expression or categorical meta data and test the predictive power of a custom variable. ROC plots show True Positive Rate (TPR) and False Positive Rate (FPR) along the y- and x-axes, respectively. A completely random classifier would appear along the diagonal line in the graph and would have Area Under the Curve (AUC) of 0.5. The curve for a good positive predictor appears in the top half of the plot (AUC > 0.5), and the curve for a good negative predictor appears in the bottom half (AUC < 0.5). Continue the tutorial to learn how to use this module.",
                  "Select sample types here to focus the analysis on specific subsets.",
                  "ROC analysis is performed between two classes in the response variable as '1' (desired outcome group) and '0' (undesired outcome group). You can specify these classes for both categorical and numeric variables in the TCGA data. Here you need to select what kind of response variable you are interested in.",
                  "You can select the categorical variable to binarize here. In the next step, you will decide which data subsets will be classified as 1 and 0.",
                  "In this box, you can select which data subsets will be classified as '1'. For example, if you have chosen 'meta.gender' previously, you can choose 'female' observations to belong to group-1 here. If the categorical variable you selected has multiple subsets, you can specify more than one subset as well.",
                  "In this box, you can select which data subsets will be classified as '0'. For example, if you have chosen 'meta.gender' previously, you can choose 'male' observations to belong to group-0 here. If the categorical variable you selected has multiple subsets, you can specify more than one subset as well.",
                  "Here, you select the predictor variable. If you enter more than one variable, their values will be averaged.",
                  "If desired, the average expression value of a specific MSigDB gene set can be added to the graph. <i> Note: You need to click on and activate 'Add MSigDB sets as a second predictor' button</i>",
                  "If you would like to include a curve for a specific MSigDB gene set, select it here."
                ))
              )
              
            } else if (input$roc_gene_selector ==  "Upload a xlsx/xls file") {
              
              data.frame(
                
                element = paste0("#", session$ns(c(NA, "roc_definition_sel + .selectize-control", "selectore + .selectize-control", "binaryone + .selectize-control ", "binarytwo + .selectize-control ", "binarythree + .selectize-control ", "genesss + .selectize-control ", NA, NA))),
                
                intro = paste(c(
                  "This is the ROC (receiver operating characteristic) analysis module. In this module, you can binarize samples based on gene expression or categorical meta data and test the predictive power of a custom variable. ROC plots show True Positive Rate (TPR) and False Positive Rate (FPR) along the y- and x-axes, respectively. A completely random classifier would appear along the diagonal line in the graph and would have Area Under the Curve (AUC) of 0.5. The curve for a good positive predictor appears in the top half of the plot (AUC > 0.5), and the curve for a good negative predictor appears in the bottom half (AUC < 0.5). Continue the tutorial to learn how to use this module.",
                  "Select sample types here to focus the analysis on specific subsets.",
                  "ROC analysis is performed between two classes in the response variable as '1' (desired outcome group) and '0' (undesired outcome group). You can specify these classes for both categorical and numeric variables in the TCGA data. Here you need to select what kind of response variable you are interested in.",
                  "You can select the categorical variable to binarize here. In the next step, you will decide which data subsets will be classified as 1 and 0.",
                  "In this box, you can select which data subsets will be classified as '1'. For example, if you have chosen 'meta.gender' previously, you can choose 'female' observations to belong to group-1 here. If the categorical variable you selected has multiple subsets, you can specify more than one subset as well.",
                  "In this box, you can select which data subsets will be classified as '0'. For example, if you have chosen 'meta.gender' previously, you can choose 'male' observations to belong to group-0 here. If the categorical variable you selected has multiple subsets, you can specify more than one subset as well.",
                  "You can upload a xlsx/xls file including your genes of interest to see them as a ROC curve. If you enter more than one variable, their values will be averaged.",
                  "If desired, the average expression value of a specific MSigDB gene set can be added to the graph.",
                  "If you would like to include a curve for a specific MSigDB gene set, select it here."
                ))
              )
              
            }
          )
        }
        
      })
      
      
      observeEvent(input$roc_help, {
        
        introjs(session, options = list(steps = roc_help_tutorial() ) )
        
      })
      
      
      
      #Reactive selectboxes.
      observeEvent(input$binaryone,{
        req(input$binaryone)
        if(length(as.vector(input$binaryone)) == 0){
          return()
        }
        
        
        # browser()
        # Old choices are retained when a new binaryone is selected. Fix this later.
        
          updateSelectizeInput(session = getDefaultReactiveDomain(),"binarytwo", choices = Xproj$a()[[input$binaryone]] , server = TRUE)

      })
      
      observeEvent(input$binaryone,{
        req(input$binaryone)
        if(length(as.vector(input$binaryone)) == 0){
          return()
        }
          updateSelectizeInput(session = getDefaultReactiveDomain(),"binarythree", choices = Xproj$a()[[input$binaryone]] , server = TRUE)
      })
      
      
      observe({updateSelectizeInput(session = getDefaultReactiveDomain(), "selectore", choices = c("Numeric Values", "Categorical Values"), server = TRUE)})
      observe({updateSelectizeInput(session = getDefaultReactiveDomain(), "one_gene", choices = colnames(Xproj$a()[, lapply(Xproj$a(), is.numeric) == TRUE, with = FALSE]), server = TRUE)})
      observe({updateSelectizeInput(session = getDefaultReactiveDomain(), "binaryone", choices = colnames(Xproj$a()[, lapply(Xproj$a(), is.factor) == TRUE, with = FALSE]), selected = "meta.definition", server = TRUE)})
      observe({updateSelectizeInput(session = getDefaultReactiveDomain(), "genesss", choices = colnames(Xproj$a()), server = TRUE)})
      observe({updateSelectizeInput(session = getDefaultReactiveDomain(), "roc_definition_sel", choices = c(Xproj$a()$meta.definition), selected = character(0), server = TRUE)})
    
      observe({
        req(input$cate)
        
        roc_subcat = names(roc_df_msigdb()[[input$cate]])
        if (length(roc_subcat) > 1)  {
          updateSelectizeInput(session,'roc_subcat', choices = roc_subcat , server = TRUE)
        } 
      })
      
      pre_df <- eventReactive(input$roc_run,{
        
        #Creating the preliminary data.
        
        pre_df <- Xproj$a()
        
        req(input$roc_definition_sel)
        
        if(length(as.vector(input$roc_definition_sel)) > 0) {
          
          #'[What is J() below?]
          # pre_df <- setDT(pre_df, key = 'meta.definition')[J(input$roc_definition_sel)]  
          pre_df <- setDT(pre_df, key = 'meta.definition')[input$roc_definition_sel]  
          pre_df
        } else if (length(as.vector(input$roc_definition_sel)) == 0){
          pre_df
        }
        
        if(input$roc_gene_selector == "Manually enter gene names"){
        # Selected gene set means as a column.
          
          pre_df[, custom_gene_set := rowMeans(.SD, na.rm = TRUE), .SDcols = c(input$genesss)]  
          
        } else if (input$roc_gene_selector ==  "Upload a xlsx/xls file") {
          
          
          uploaded_roc_csv <- input$roc_csv
          
          selected_roc_csv <- as.data.frame(read_excel(uploaded_roc_csv$datapath, sheet = 1, col_names = F))
          
          colnames(selected_roc_csv)[1] <- "Genes" 
          
          roc_same_gene_names = intersect(selected_roc_csv[["Genes"]], colnames(pre_df))
          
          roc_csv_selected_cols <- c(roc_same_gene_names)
          
          pre_df[, custom_gene_set := rowMeans(.SD, na.rm = TRUE), .SDcols = c(roc_csv_selected_cols)]
        }
        
        if(input$selectore == "Numeric Values"){
          
          # Selected Gene Value
          mid_value_roc <- ifelse(input$keep_mid_covar, "mid", NA)
          
          pre_df[, (input$one_gene) := ifelse(pre_df[[input$one_gene]] >= quantile(pre_df[[input$one_gene]], (100-input$hi_cutoff_covar)/100, na.rm = T), 1, ifelse(pre_df[[input$one_gene]] <= quantile(pre_df[[input$one_gene]], input$lo_cutoff_covar/100, na.rm = T), 0, mid_value_roc))]
          
        }else{
          # Selected Binary Value
          
          pre_df <- pre_df %>% 
            mutate(roccurve = case_when(
              get(input$binaryone) %in% input$binarytwo ~ 1,
              get(input$binaryone) %in% input$binarythree ~ 0,
              .default = NA
            ))
        }
      })
      
      #'[unnecessary file path paste construct?]
      # roc_df_msigdb <- reactive({df_msigdb <- readRDS(paste0("genesets/", "msigdb_long", ".rds"))})
      
      roc_df_msigdb <- reactive({readRDS("genesets/msigdb_long_w_immth.rds")})
      
      df_gene_sets <- reactive({ 
        
        req(roc_df_msigdb())
        
        #Preparation of Human MSigDB genesets.
        
        df_msigdb <- roc_df_msigdb()
        
        #'[Can this be better designed?]
        if(input$show_msigdb_gene_sets == TRUE){
          
            if(input$cate %in% c("C2","C3","C4","C5","C7")) {
              
              df_msigdb2 = names(df_msigdb[[input$cate]][[input$roc_subcat]])
              
            } else {
              df_msigdb2 = names(df_msigdb[[input$cate]][[1]])
            }
          # return(df_msigdb2)
          
        } else if(input$show_msigdb_gene_sets == FALSE){
          
          return({
            #'[why is this needed?]
            df_msigdb3 <- NULL
          })
        }
      })

      observe({
        
        req(roc_df_msigdb())
        
        req(df_gene_sets())
        
        if(input$cate %in% c("C2","C3","C4","C5","C7")) {
          
          
          roc_path = df_gene_sets()
          updateSelectizeInput(session,'roc_chosen_pathway', choices = roc_path , server = TRUE)
          
        } else {
          
          roc_path = df_gene_sets()
          updateSelectizeInput(session,'roc_chosen_pathway', choices = roc_path , server = TRUE)
        }
        
      })

      df_final_data <- eventReactive(input$roc_run,{
        
        #Preparation of final data.
        
        req(pre_df())
        
        if(input$show_msigdb_gene_sets == TRUE){
          
          df_msigdb <- readRDS(paste0("genesets/", "msigdb_long", ".rds"))
          
          if(input$cate %in% c("C2","C3","C4","C5","C7")) {
            
            roc_msigdb_genes <- df_msigdb[[input$cate]][[input$roc_subcat]][[input$roc_chosen_pathway]]
            
          } else {
            
            roc_msigdb_genes <- df_msigdb[[input$cate]][[1]][[input$roc_chosen_pathway]]
          }

          #Take the subset of chosen Human MsigDB geneset.
          
          df_final_gene_sets <- roc_msigdb_genes

          # Drop and the Human MsigDB genes which are not in our data.
          
          df_unfiltered <- pre_df()
          
          same_hallmarks_names = intersect(df_final_gene_sets, colnames(df_unfiltered))
          
          df_unfiltered[, selected_msigdb_gene_set := rowMeans(.SD, na.rm = TRUE), .SDcols = same_hallmarks_names]  
          
          df_unfiltered
          
        } else if(input$show_msigdb_gene_sets == FALSE){
          
          df_final_gene_sets <- pre_df()
          
        }
        
        
      })
      
      df_gene_set_table_calc <- eventReactive(input$roc_run, {

        if(input$show_msigdb_gene_sets == TRUE){
          
          df_msigdb <- readRDS(paste0("genesets/", "msigdb_long", ".rds"))
          
          if(input$cate %in% c("C2","C3","C4","C5","C7")) {
            
            roc_msigdb_genes <- df_msigdb[[input$cate]][[input$roc_subcat]][[input$roc_chosen_pathway]]
            
          } else {
            
            roc_msigdb_genes <- df_msigdb[[input$cate]][[1]][[input$roc_chosen_pathway]]
          }
          
          #Take the subset of chosen Human MsigDB geneset.
          
          df_final_gene_sets <- roc_msigdb_genes
          
          # Drop and the Human MsigDB genes which are not in our data.
          
          same_hallmarks_names = intersect(df_final_gene_sets, colnames(pre_df()))
          
          df_same_hallmarks_names <- as.data.frame(same_hallmarks_names)

          colnames(df_same_hallmarks_names)[which(names(df_same_hallmarks_names) == "same_hallmarks_names")] <- "Intersected genes between MSigDB gene sets and chosen cancer data"
          
          df_same_hallmarks_names <- as.data.frame(df_same_hallmarks_names)

        } else if(input$show_msigdb_gene_sets == FALSE){
          
          df_final_gene_sets <- df_gene_sets()
          
          df_final_gene_sets
        }
        
        
      })
      
      roc_multi_plot <- eventReactive(input$roc_run, {
        
        validate(need(input$roc_run, "Enter interactions and click Run ROC!"))
        
        if(input$selectore == "Numeric Values"){
          
          #Calculation of plot with the chosen numerical value.
          
          if(input$show_msigdb_gene_sets == TRUE){
            
            #Calculation of plot with the chosen multiple genes.
            
            validate(need(input$roc_definition_sel, "Please select a sample type"))
            validate(need(input$roc_chosen_pathway, "Please select an MSigDB gene set"))
            
            if(input$roc_gene_selector == "Manually enter gene names"){

              validate(need(input$genesss, "Please select genes to create a custom predictor (multiple genes will be averaged)"))
              
            } else if (input$roc_gene_selector ==  "Upload a xlsx/xls file") {
              
              validate(need(input$roc_csv, "Please upload a xlsx/xls file to create a custom predictor (multiple genes will be averaged)"))
              
              }
            
            longtest <- melt_roc(df_final_data(), input$one_gene, c("custom_gene_set", "selected_msigdb_gene_set"))
            multiplot1 <- ggplot(longtest, aes(d = D, m = M, color = name)) + geom_roc() + style_roc() + theme(legend.text = element_text(size = 18)) + geom_abline(slope = 1, intercept = 0, linetype = 2, color = "grey50") 
            
            return(print(multiplot1))
          } else if (input$show_msigdb_gene_sets == FALSE){
            
            #Calculation of plot with the chosen single gene.
            
            validate(need(input$roc_definition_sel, "Please select a sample type"))
            validate(need(input$one_gene, "Please choose gene expression data"))
            
            if(input$roc_gene_selector == "Manually enter gene names"){
              
              validate(need(input$genesss, "Please select genes to create a custom predictor (multiple genes will be averaged)"))
              
            } else if (input$roc_gene_selector ==  "Upload a xlsx/xls file") {
              
              validate(need(input$roc_csv, "Please upload a xlsx/xls file to create a custom predictor (multiple genes will be averaged)"))
              
            }
            
            basicplot <- ggplot(df_final_data(), aes(d = df_final_data()[[input$one_gene]], m = custom_gene_set)) + geom_roc() + geom_abline(slope = 1, intercept = 0, linetype = 2, color = "#030300") + coord_fixed()
            styledplotroc <- basicplot + style_roc() + annotate("text", x =.75, y =.25, label = paste ("AUC =", round (calc_auc (basicplot) ["AUC"], 2))) 
            
            return(print(styledplotroc))
          }
          
        }else{
          
          if(input$binaryone == "meta.definition"){
            validate(need(all(input$binarytwo %in% input$roc_definition_sel) == TRUE, "Please add the binarization meta.definition subtype to the first input box to not filter it in the data."))
            validate(need(all(input$binarythree %in% input$roc_definition_sel) == TRUE, "Please add the binarization meta.definition subtype to the first input box to not filter it in the data."))
            
          } else
            
          #Calculation of plot with the chosen binary value.
          
          validate(need(input$roc_definition_sel, "Please select a sample type"))
          validate(need(input$binaryone, "Please choose numeric variable to binarize"))
          validate(need(input$binarytwo, "Please choose value(s) to classify as group-1"))
          validate(need(input$binarythree, "Please choose value(s) to classify as group-0"))
          
          if(input$roc_gene_selector == "Manually enter gene names"){
            
            validate(need(input$genesss, "Please select genes to create a custom predictor (multiple genes will be averaged)"))
            
          } else if (input$roc_gene_selector ==  "Upload a xlsx/xls file") {
            
            validate(need(input$roc_csv, "Please upload a xlsx/xls file to create a custom predictor (multiple genes will be averaged)"))
            
          }
          
          if(input$show_msigdb_gene_sets == TRUE){
            
            #Calculation of plot with the chosen multiple genes.
            validate(need(input$roc_chosen_pathway, "Please select an MSigDB gene set"))
            
            longtest <- melt_roc(df_final_data(), "roccurve", c("custom_gene_set", "selected_msigdb_gene_set"))
            multiplot2 <- ggplot(longtest, aes(d = D, m = M, color = name)) + geom_roc() + style_roc() + theme(legend.text = element_text(size = 18)) + geom_abline(slope = 1, intercept = 0, linetype = 2, color = "grey50") 
            
            return(print(multiplot2))
            
          } else if (input$show_msigdb_gene_sets == FALSE){
            
            #Calculation of plot with the chosen single gene.
            
            basicplot <- ggplot(df_final_data(), aes(d = roccurve, m = custom_gene_set)) + geom_roc() + geom_abline(slope = 1, intercept = 0, linetype = 2, color = "#030300") + coord_fixed()
            styledplot <- basicplot + style_roc() + annotate("text", x =.75, y =.25, label = paste ("AUC =", calc_auc (basicplot) ["AUC"])) 
            return(print(styledplot))
            
          }
        }
        
        
      })
      
      
      output$multi_plot <- renderPlot({
        
        # Output of the plot
        
        req(roc_multi_plot())
        
        print(roc_multi_plot())
        
      })
      
      
      roc_auc_data <- eventReactive(input$roc_run, {
        
        # Calculation for the area under curve (AUC).
        
        validate(need(input$roc_run, "Enter interactions and click Run ROC!"))
        
        if(input$selectore == "Numeric Values"){
          
          if(input$roc_gene_selector == "Manually enter gene names"){
            
            validate(need(input$genesss, "Please select genes to create a custom predictor (multiple genes will be averaged)"))
            
          } else if (input$roc_gene_selector ==  "Upload a xlsx/xls file") {
            
            validate(need(input$roc_csv, "Please upload a xlsx/xls file to create a custom predictor (multiple genes will be averaged)"))
            
          }
          
          fortable1 <- calc_auc(roc_multi_plot())
          return(fortable1)
          
        }else{
          
          validate(need(input$binaryone, "Please choose numeric variable to binarize"))
          validate(need(input$binarytwo, "Please choose value(s) to be classified as group-1"))
          validate(need(input$binarythree, "Choose second value(s) to be classified as group-0"))
          
          if(input$roc_gene_selector == "Manually enter gene names"){
            
            validate(need(input$genesss, "Please select genes to create a custom predictor (multiple genes will be averaged)"))
            
          } else if (input$roc_gene_selector ==  "Upload a xlsx/xls file") {
            
            validate(need(input$roc_csv, "Please upload a xlsx/xls file to create a custom predictor (multiple genes will be averaged)"))
            
          }
          
          fortable2 <- calc_auc(roc_multi_plot())
          return(fortable2)
          
        }
        
        
      })
      
      
      output$auctable <- DT::renderDataTable({
        
        # Output for the area under curve (AUC).
        
        roc_auc_data()
        
      })
      
      observeEvent(input$roc_run, {
        
        #Table output of the intersected gene names between the xlsx/xls file and selected the cancer data.
        
        output$intersect_genes_table <- DT::renderDataTable({

          if(input$roc_gene_selector ==  "Upload a xlsx/xls file"){
            
            req(pre_df())
            
            validate(need(input$roc_csv, "Please upload a xlsx/xls file to create a custom predictor (multiple genes will be averaged)"))
            
            req(input$roc_definition_sel)
            
            uploaded_roc_csv <- input$roc_csv
            
            selected_roc_csv <- as.data.frame(read_excel(uploaded_roc_csv$datapath, sheet = 1, col_names = F))
            
            colnames(selected_roc_csv)[1] <- "Genes" 
            
            roc_same_gene_names = intersect(selected_roc_csv[["Genes"]], colnames(pre_df()))
            
            intersect_data_frame <- as.data.frame(roc_same_gene_names)
            
            colnames(intersect_data_frame)[which(names(intersect_data_frame) == "roc_same_gene_names")] <- "Intersected genes between xlsx/xls file and chosen cancer data"
            
            intersect_data_frame <- as.data.frame(intersect_data_frame)
            
          }
          
        })
        
      })
      
      
      observeEvent(input$roc_run, {
        
        #Output for the Human MSigDB geneset table.
        
        output$gene_set_table <- DT::renderDataTable({
          
          if(input$show_msigdb_gene_sets == TRUE){
            
            validate(need(input$roc_run, "Enter interactions and click Run ROC!"))
            
            df_gene_set_table_calc()
            
          }
          
        })
        
      })
      
      output$downloadPlot5 <- downloadHandler(
        filename = function() {
          paste("ROC_plot.png")
        },
        content = function(file) {
          
          png(file, width = 800, height = 500)
          print(roc_multi_plot())
          dev.off()
          
        })
      
      
    }
  )
}



